NEI.override("EnderIO", "blockCapBank", [1, 2, 3]);
NEI.override("EnderIO", "blockBuffer", [0, 1, 2]);
NEI.hide("EnderIO", "blockLightNode");
NEI.hide("Thaumcraft", "blockEldritchNothing");
NEI.hide("Thaumcraft", "blockPortalEldritch");
NEI.hide("witchery", "spiritportal");
NEI.hide("witchery", "tormentportal");
NEI.hide("harvestcraft", "chocolaterollItem");
NEI.hide("compacter", "Cobbler");
NEI.hide("extracells", "certustank");
NEI.hide("Botania", "fakeAir");
NEI.hide("Botania", "gaiaHeadBlock");
NEI.hide("CarpentersBlocks", "CarpentersBlocks");
NEI.hide("CarpentersBlocks", "blockCarpentersBed");
NEI.hide("CarpentersBlocks", "blockCarpentersDoor");
NEI.hide("OpenBlocks", "grave");
NEI.hide("Thaumcraft", "blockWarded");
NEI.hide("Thaumcraft", "blockHole");
NEI.override("ExtraTiC", "funStuffIngot", [0, 1]);
NEI.override("ExtraTiC", "blockFunStuff", [0, 1]);
NEI.hide("BigReactors", "BRMultiblockCreativePart");
NEI.hide("Natura", "N Crops");
